name:           nalkuatov-kz

executables:
  telegram-notifier:
    main:             Server.hs
    source-dirs:      notifier/src
    default-extensions:
      - DerivingStrategies
      - OverloadedStrings
      - RankNTypes
      - FlexibleContexts
      - DataKinds
      - TypeOperators
    ghc-options:
      - -threaded
    dependencies:
      - base == 4.*
      - aeson
      - mtl
      - text
      - servant
      - servant-server
      - servant-client
      - exceptions

  site:
    main:             site.hs
    source-dirs:      .
    ghc-options:
      - -threaded
    dependencies:
      - hakyll == 4.13.*
      - base == 4.*
